# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.cache/wt} [current_project]
set_property parent.project_path {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog {
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/define.vh}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/mips_define.vh}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/function.vh}
}
set_property file_type "Verilog Header" [get_files {{E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/define.vh}}]
set_property file_type "Verilog Header" [get_files {{E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/mips_define.vh}}]
set_property file_type "Verilog Header" [get_files {{E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/function.vh}}]
read_verilog -library xil_defaultlib {
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/regfile.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/CP0.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/alu.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/controller.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/datapath.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/mips_core.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/parallel2serial.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/data_ram.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/inst_rom.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/my_clk_gen.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/clk_diff.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/btn_scan.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/display.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/vga_debug.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/mips.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/vga.v}
  {E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/mips_top.v}
}
read_edif {{E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/sources_1/imports/exp3_student/vga_debug.ngc}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/constrs_1/imports/Jinhong/SwordV4_contraints.xdc}}
set_property used_in_implementation false [get_files {{E:/My universe/university/Course/Computer Architecture/Lab/Source/Exp7/Exp7.srcs/constrs_1/imports/Jinhong/SwordV4_contraints.xdc}}]


synth_design -top mips_top -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef mips_top.dcp

catch { report_utilization -file mips_top_utilization_synth.rpt -pb mips_top_utilization_synth.pb }
